// Code generated by "stringer -type=GameState"; DO NOT EDIT

package engine

import "fmt"

const _GameState_name = "CombatRecoverChoosingFirstPlayerEnd"

var _GameState_index = [...]uint8{0, 6, 13, 32, 35}

func (i GameState) String() string {
	if i >= GameState(len(_GameState_index)-1) {
		return fmt.Sprintf("GameState(%d)", i)
	}
	return _GameState_name[_GameState_index[i]:_GameState_index[i+1]]
}
