// Code generated by "stringer -type=Stance"; DO NOT EDIT

package engine

import "fmt"

const _Stance_name = "SnakeTigerDragon"

var _Stance_index = [...]uint8{0, 5, 10, 16}

func (i Stance) String() string {
	if i < 0 || i >= Stance(len(_Stance_index)-1) {
		return fmt.Sprintf("Stance(%d)", i)
	}
	return _Stance_name[_Stance_index[i]:_Stance_index[i+1]]
}
